micronaut:
  application:
    name: expenShare
  serde:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    time-zone: UTC

datasources:
  default:
    url: jdbc:h2:mem:devDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    entity-scan:
      packages: com.example.model.entity
kafka:
  bootstrap:
    servers: localhost:29092
logger:
  levels:
    ROOT: INFO
